name: deploy_after_merge

on:
  push:
    branches: 
     - release

jobs:
  job_1:
    name: prefer
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a multi-line script
      run: |
        touch ./ios/Runner/GoogleService-Info.plist
        touch ./android/app/google-services.json

    - name: wget
      uses: wei/wget@v1
      with:
        args: ${{ secrets.FIREBASE_IOS }} -O ./ios/Runner/GoogleService-Info.plist

    - name: wget
      uses: wei/wget@v1
      with:
        args: ${{ secrets.FIREBASE_ANDROID }} -O ./android/app/google-services.json

  job_2:
    name: flutter
    needs: job_1
    runs-on: macos-latest
    steps:

    - uses: subosito/flutter-action@v1.1.1
      with:
        channel: 'stable'
          
    - name: flutter pub get
      run: flutter pub get

    - name: flutter build ios
      run: flutter build ios --release --no-codesign

    - name: flutter build android
      run: flutter build apk --release

    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.1.1
      with:
        appId: ${{secrets.FIREBASE_ANDROID_APPID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: zwtin
        file: ./build/app/outputs/apk/release/app-release.apk

