name: deploy_after_merge

on:
  push:
    branches: 
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a multi-line script
      run: |
          touch ./ios/Runner/GoogleService-Info.plist
          touch ./android/app/google-services.json

    - name: wget
      uses: wei/wget@v1
      with:
        args: ${{ secrets.FIREBASE_IOS }} -O ./ios/Runner/GoogleService-Info.plist

    - name: wget
      uses: wei/wget@v1
      with:
        args: ${{ secrets.FIREBASE_ANDROID }} -O ./android/app/google-services.json

    - uses: subosito/flutter-action@v1.1.1
      with:
          channel: 'dev'
          
    - name: Build APK
      run: |
          flutter pub get
          flutter build apk
    - name: Run tests
      run: pub run test
