name: deploy_after_merge

on:
  push:
    branches: 
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.1.1
      with:
          channel: 'dev'
          
    - name: Build APK
      run: |
          flutter pub get
          flutter build apk
    - name: Run tests
      run: pub run test
